// All visible copy lives here, in Turkish, English and German.

export const content = {
  en: {
    meta: {
      title: 'IMEX Inspection | Maritime and logistics inspections',
      description:
        'IMEX Inspection provides independent, accredited third-party supervision, inspection and consultancy services in the maritime and logistics sector.',
    },
    nav: {
      services: 'Services',
      about: 'About',
      contact: 'Contact',
      menu: 'Menu',
      home: 'IMEX Inspection, home',
      langLabel: 'Change language',
    },
    hero: {
      brand: 'IMEX Inspection',
      slogan: 'Control In Operations, Trust In Trade.',
    },
    services: {
      title: 'Solutions',
      groups: ['Supervision', 'Quality', 'Quantity', 'Sampling'],
      items: [
        'Pre-shipment supervision',
        'Loading and discharge supervision',
        'Cargo condition / damage assessment supervision',
        'Tally',
        'Cargo quantity determination (draft, ullage)',
        'Sealing / seal-breaking supervision',
        'Lashing',
        'Container supervision',
        'Vessel hold / tank inspection',
        'Weighbridge supervision',
        'Fuel quantity determination (bunker survey)',
      ],
    },
    about: {
      title: 'About Us',
      text: 'IMEX Denetim ve Danışmanlık Hizmetleri A.Ş. provides its clients with independent, accredited third-party supervision, inspection and consultancy services for their commercial activities.',
    },
    contact: {
      title: 'Get in Touch',
      address: 'Address',
      email: 'E-mail',
      mapLabel: 'Ankara Head Office',
      directions: 'Get directions',
      form: {
        name: 'Full name',
        company: 'Company',
        email: 'E-mail',
        phone: 'Phone',
        category: 'Category',
        categoryPlaceholder: 'Please select',
        categories: [
          'Inspection / Supervision Request',
          'Quotation Request',
          'Information and Consultancy',
          'Partnership Request',
          'Feedback',
          'Other',
        ],
        message: 'Message',
        optional: 'optional',
        kvkkPre: 'I have read the ',
        kvkkLink: 'KVKK Privacy Notice',
        kvkkPost: ' and understand how my data is processed.',
        send: 'Send request',
        sending: 'Sending…',
        success: 'Request sent. We will get back to you by e-mail.',
        error: 'The request could not be sent. Please try again, or write to us directly.',
      },
    },
    legal: { updated: 'Last updated' },
    notFound: {
      title: 'Page not found',
      text: 'The page you are looking for does not exist or has moved.',
      home: 'Home',
    },
    footer: {
      rights: 'All rights reserved.',
      privacy: 'KVKK Privacy Notice',
    },
  },

  tr: {
    meta: {
      title: 'IMEX Inspection | Denizcilik ve lojistik denetimleri',
      description:
        'IMEX Inspection, denizcilik ve lojistik sektöründe bağımsız, akredite üçüncü taraf gözetim, denetim ve danışmanlık hizmetleri sunar.',
    },
    nav: {
      services: 'Hizmetler',
      about: 'Hakkımızda',
      contact: 'İletişim',
      menu: 'Menü',
      home: 'IMEX Inspection, ana sayfa',
      langLabel: 'Dili değiştir',
    },
    hero: {
      brand: 'IMEX Inspection',
      slogan: 'Operasyonda Kontrol, Ticarette Güven.',
    },
    services: {
      title: 'Çözümler',
      groups: ['Gözetim', 'Kalite', 'Miktar', 'Numune'],
      items: [
        'Yükleme öncesi gözetim',
        'Yükleme ve tahliye gözetimi',
        'Kargo kondisyon / hasar tespit gözetimi',
        'Tally',
        'Yük miktarı ölçüm tespiti (draft, ullage)',
        'Mühürleme / mühür kırma gözetimi',
        'Lashing',
        'Konteyner gözetimi',
        'Gemi ambar / tank kontrolü',
        'Kantar gözetimi',
        'Yakıt miktarı tespiti (bunker survey)',
      ],
    },
    about: {
      title: 'Hakkımızda',
      text: 'IMEX Denetim ve Danışmanlık Hizmetleri A.Ş., müşterilerine ticari faaliyetleri için üçüncü taraf bağımsız, akredite, gözetim, denetim ve danışmanlık hizmetleri sunar.',
    },
    contact: {
      title: 'İletişime Geçin',
      address: 'Adres',
      email: 'E-posta',
      mapLabel: 'Ankara Baş Ofis',
      directions: 'Yol tarifi al',
      form: {
        name: 'Ad soyad',
        company: 'Şirket',
        email: 'E-posta',
        phone: 'Telefon',
        category: 'Kategori',
        categoryPlaceholder: 'Seçiniz',
        categories: [
          'Denetim / Gözetim Talebi',
          'Teklif Talebi',
          'Bilgi ve Danışmanlık',
          'İş Birliği Talebi',
          'Geri Bildirim',
          'Diğer',
        ],
        message: 'Mesaj',
        optional: 'isteğe bağlı',
        kvkkPre: '',
        kvkkLink: 'KVKK Aydınlatma Metni’ni',
        kvkkPost: ' okudum, kişisel verilerimin nasıl işlendiğini anladım.',
        send: 'Talebi gönder',
        sending: 'Gönderiliyor…',
        success: 'Talebiniz gönderildi. E-posta ile size dönüş yapacağız.',
        error: 'Talep gönderilemedi. Lütfen tekrar deneyin ya da bize doğrudan yazın.',
      },
    },
    legal: { updated: 'Son güncelleme' },
    notFound: {
      title: 'Sayfa bulunamadı',
      text: 'Aradığınız sayfa mevcut değil veya taşınmış.',
      home: 'Ana sayfa',
    },
    footer: {
      rights: 'Tüm hakları saklıdır.',
      privacy: 'KVKK Aydınlatma Metni',
    },
  },

  de: {
    meta: {
      title: 'IMEX Inspection | Inspektionen in Schifffahrt und Logistik',
      description:
        'IMEX Inspection bietet unabhängige, akkreditierte Überwachungs-, Inspektions- und Beratungsdienstleistungen in der Schifffahrts- und Logistikbranche.',
    },
    nav: {
      services: 'Leistungen',
      about: 'Über uns',
      contact: 'Kontakt',
      menu: 'Menü',
      home: 'IMEX Inspection, Startseite',
      langLabel: 'Sprache wechseln',
    },
    hero: {
      brand: 'IMEX Inspection',
      slogan: 'Kontrolle Im Betrieb, Vertrauen Im Handel.',
    },
    services: {
      title: 'Lösungen',
      groups: ['Überwachung', 'Qualität', 'Menge', 'Probenahme'],
      items: [
        'Vorverladungsüberwachung',
        'Verladungs- und Löschüberwachung',
        'Zustands- / Schadensfeststellung der Ladung',
        'Tally (Zählung)',
        'Ladungsmengenermittlung (Tiefgang, Ullage)',
        'Verplombung / Plombenbruch-Überwachung',
        'Lashing (Ladungssicherung)',
        'Containerüberwachung',
        'Laderaum- / Tankinspektion',
        'Waagenüberwachung',
        'Bunkermengenermittlung (Bunker Survey)',
      ],
    },
    about: {
      title: 'Über uns',
      text: 'Die IMEX Denetim ve Danışmanlık Hizmetleri A.Ş. bietet ihren Kunden unabhängige, akkreditierte Drittüberwachungs-, Inspektions- und Beratungsdienstleistungen für ihre Handelstätigkeiten.',
    },
    contact: {
      title: 'Kontakt aufnehmen',
      address: 'Adresse',
      email: 'E-Mail',
      mapLabel: 'Ankara Hauptsitz',
      directions: 'Route berechnen',
      form: {
        name: 'Vollständiger Name',
        company: 'Unternehmen',
        email: 'E-Mail',
        phone: 'Telefon',
        category: 'Kategorie',
        categoryPlaceholder: 'Bitte auswählen',
        categories: [
          'Inspektions-/Überwachungsanfrage',
          'Angebotsanfrage',
          'Information und Beratung',
          'Kooperationsanfrage',
          'Feedback',
          'Sonstiges',
        ],
        message: 'Nachricht',
        optional: 'optional',
        kvkkPre: 'Ich habe den ',
        kvkkLink: 'KVKK-Datenschutzhinweis',
        kvkkPost: ' gelesen und verstehe, wie meine Daten verarbeitet werden.',
        send: 'Anfrage senden',
        sending: 'Wird gesendet…',
        success: 'Anfrage gesendet. Wir melden uns per E-Mail bei Ihnen.',
        error: 'Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut oder schreiben Sie uns direkt.',
      },
    },
    legal: { updated: 'Letzte Aktualisierung' },
    notFound: {
      title: 'Seite nicht gefunden',
      text: 'Die gesuchte Seite existiert nicht oder wurde verschoben.',
      home: 'Startseite',
    },
    footer: {
      rights: 'Alle Rechte vorbehalten.',
      privacy: 'KVKK-Datenschutzhinweis',
    },
  },
};
